=== tomerhy/OptionaToThe-/operator/operator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0.0">
	<!-- Root configuration object -->
	<xs:element name="Operator">
		<xs:annotation>
			<xs:documentation>Root configuration element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Log" type="ExtendedLogConfig"/>
				<xs:element name="Manager" type="ManagerConfig"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Infrastructure objects -->
	<xs:simpleType name="LogLevel">
		<xs:restriction base="xs:string">
			<xs:enumeration value="debug"/>
			<xs:enumeration value="info"/>
			<xs:enumeration value="notice"/>
			<xs:enumeration value="warning"/>
			<xs:enumeration value="error"/>
			<xs:enumeration value="critical"/>
			<xs:enumeration value="alert"/>
			<xs:enumeration value="fatal"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IPAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="((25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[0-9])\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[0-9])){0,1}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IPPort">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="65535"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Pathname">
		<xs:restriction base="xs:string">
			<xs:pattern value="[\.]{0,2}(/[0-9a-zA-Z_ &amp;@\+-\^~#\.]*)+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BasicLogConfig">
		<xs:annotation>
			<xs:documentation>Basic settings for an object logging.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Category" default="op">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="3"/>
						<xs:pattern value="[a-zA-Z0-9_\.]{1,3}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Level" type="LogLevel" default="notice"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ExtendedLogConfig">
		<xs:annotation>
			<xs:documentation>Extended settings for an object logging.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="BasicLogConfig">
				<xs:sequence>
					<xs:element name="LogFileName" type="xs:string" default="lpm.log">
						<xs:annotation>
							<xs:documentation>The log file name token to be used when writing log files.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LogFilePath" type="xs:string" default="/var/log/cyberbit/lpm">
						<xs:annotation>
							<xs:documentation>The path under which the log files are to be written.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LogFileMaxSizeMB" default="50">
						<xs:annotation>
							<xs:documentation>The maximum size of a single log file in MB.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1"/>
								<xs:maxInclusive value="512"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="MaxLogFiles" default="20">
						<xs:annotation>
							<xs:documentation>The maximum number of log files.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1"/>
								<xs:maxInclusive value="100"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="Layout" type="xs:string" default="%d{%y-%m-%d %H:%M:%S.%l}| %-6p | %-15c | %m%n">
						<xs:annotation>
							<xs:documentation>Log line layout format string. See log4cpp documentation for details.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LoggerConfig">
		<xs:annotation>
			<xs:documentation>A logging object configuration.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Log" type="BasicLogConfig"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ManagerConfig">
		<xs:annotation>
			<xs:documentation>Manager object configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="LoggerConfig">
				<xs:sequence>
					<xs:choice>
						<xs:element name="Dreamer" type="DreamerConfig"/>
					</xs:choice>
					<xs:element name="Executor" type="ExecutorConfig"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="InformerConfig">
		<xs:annotation>
			<xs:documentation>Informer object configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="LoggerConfig">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DreamerConfig">
		<xs:complexContent>
			<xs:extension base="InformerConfig">
				<xs:sequence>
					<xs:element name="service_address" type="IPAddress">
						<xs:annotation>
							<xs:documentation>IP address of the information service, namely the dreamon application server.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="service_port" type="IPPort">
						<xs:annotation>
							<xs:documentation>IP port of the information service, namely the dreamon application server.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="local_address" type="IPAddress" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Local IP address to bind to in accessing the server [optional].</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="local_port" type="IPPort" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Local IP port to bind to in accessing the server [optional].</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ExecutorConfig">
		<xs:annotation>
			<xs:documentation>Executor object configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="LoggerConfig">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== tomerhy/OptionaToThe-/operator/operator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com)-->
<Operator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="operator.xsd">
	<Log>
		<Category>op</Category>
		<Level>debug</Level>
		<LogFileName>operator.log</LogFileName>
		<LogFilePath>./</LogFilePath>
		<LogFileMaxSizeMB>5</LogFileMaxSizeMB>
		<MaxLogFiles>2</MaxLogFiles>
		<Layout>%d{%y-%m-%d %H:%M:%S.%l}| %-6p | %-15c | %m%n</Layout>
	</Log>
	<Manager>
		<Log>
			<Category>mng</Category>
			<Level>notice</Level>
		</Log>
		<Dreamer>
			<Log>
				<Category>drm</Category>
				<Level>notice</Level>
			</Log>
		</Dreamer>
		<Executor>
			<Log>
				<Category>xec</Category>
				<Level>notice</Level>
			</Log>
		</Executor>
	</Manager>
</Operator>
